// <auto-generated />
using System;
using FastFoodApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable enable

namespace FastFoodApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250807000001_AddPhuongThucThanhToanManual")]
    partial class AddPhuongThucThanhToanManual
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // No need for detailed model here, as we're only adding a column
        }
    }
}
