// <auto-generated />
using System;
using FastFoodApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastFoodApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250807111019_UpdateMembershipThresholds")]
    partial class UpdateMembershipThresholds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASM1.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemID"));

                    b.Property<string>("CartSessionID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartItemID");

                    b.HasIndex("ProductID");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ASM1.Models.Combo", b =>
                {
                    b.Property<int>("MaCombo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCombo"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("HinhAnh")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCombo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MaCombo");

                    b.ToTable("Combos");

                    b.HasData(
                        new
                        {
                            MaCombo = 1,
                            Gia = 89000m,
                            MoTa = "1 Burger Zinger + 1 Khoai Tây Chiên (Vừa) + 1 Pepsi Lon",
                            TenCombo = "Combo Zinger"
                        },
                        new
                        {
                            MaCombo = 2,
                            Gia = 92000m,
                            MoTa = "2 Miếng Gà Rán + 1 Khoai Tây Chiên (Vừa) + 1 Pepsi Lon",
                            TenCombo = "Combo Gà Rán 1 người"
                        },
                        new
                        {
                            MaCombo = 3,
                            Gia = 199000m,
                            MoTa = "3 Miếng Gà Rán + 1 Burger Tôm + 2 Khoai Tây Chiên (Vừa) + 2 Pepsi Lon",
                            TenCombo = "Combo Nhóm 2 người"
                        },
                        new
                        {
                            MaCombo = 4,
                            Gia = 69000m,
                            MoTa = "1 Cơm Gà Rán + 1 Salad + 1 Pepsi Lon",
                            TenCombo = "Combo Cơm Gà"
                        });
                });

            modelBuilder.Entity("ASM1.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<string>("DiaChiGiaoHang")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("ASM1.Models.LoaiMonAn", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiMonAns");

                    b.HasData(
                        new
                        {
                            MaLoai = 1,
                            TenLoai = "Gà Rán & Gà Quay"
                        },
                        new
                        {
                            MaLoai = 2,
                            TenLoai = "Burger & Cơm"
                        },
                        new
                        {
                            MaLoai = 3,
                            TenLoai = "Thức Ăn Nhẹ"
                        },
                        new
                        {
                            MaLoai = 4,
                            TenLoai = "Tráng Miệng & Thức Uống"
                        });
                });

            modelBuilder.Entity("ASM1.Models.MonAn", b =>
                {
                    b.Property<int>("MaMonAn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMonAn"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("HinhAnh")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("bit");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<string>("TenMonAn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MaMonAn");

                    b.HasIndex("MaLoai");

                    b.ToTable("MonAns");

                    b.HasData(
                        new
                        {
                            MaMonAn = 1,
                            Gia = 36000m,
                            IsNew = false,
                            IsPopular = true,
                            MaLoai = 1,
                            MoTa = "Gà Rán Cay Hot & Spicy.",
                            Rating = 4.7999999999999998,
                            ReviewCount = 250,
                            TenMonAn = "1 Miếng Gà Rán Hot & Spicy"
                        },
                        new
                        {
                            MaMonAn = 2,
                            Gia = 105000m,
                            IsNew = false,
                            IsPopular = true,
                            MaLoai = 1,
                            MoTa = "Combo 3 miếng Gà Rán Cay Hot & Spicy.",
                            OriginalPrice = 108000m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 180,
                            TenMonAn = "3 Miếng Gà Rán Hot & Spicy"
                        },
                        new
                        {
                            MaMonAn = 3,
                            Gia = 69000m,
                            IsNew = true,
                            IsPopular = false,
                            MaLoai = 1,
                            MoTa = "Gà Quay Giấy Bạc đậm đà hương vị Việt.",
                            Rating = 4.9000000000000004,
                            ReviewCount = 150,
                            TenMonAn = "1 Miếng Gà Quay Giấy Bạc"
                        },
                        new
                        {
                            MaMonAn = 4,
                            Gia = 55000m,
                            IsNew = false,
                            IsPopular = true,
                            MaLoai = 2,
                            MoTa = "Burger Zinger với 100% thịt phi lê gà cay giòn.",
                            Rating = 4.9000000000000004,
                            ReviewCount = 310,
                            TenMonAn = "Burger Zinger"
                        },
                        new
                        {
                            MaMonAn = 5,
                            Gia = 45000m,
                            IsNew = false,
                            IsPopular = false,
                            MaLoai = 2,
                            MoTa = "Cơm Gà Rán kèm xà lách và sốt.",
                            Rating = 4.5999999999999996,
                            ReviewCount = 120,
                            TenMonAn = "Cơm Gà Rán"
                        },
                        new
                        {
                            MaMonAn = 6,
                            Gia = 45000m,
                            IsNew = true,
                            IsPopular = false,
                            MaLoai = 2,
                            MoTa = "Burger nhân tôm tẩm bột chiên giòn, kết hợp với sốt đặc biệt.",
                            Rating = 4.5999999999999996,
                            ReviewCount = 90,
                            TenMonAn = "Burger Tôm"
                        },
                        new
                        {
                            MaMonAn = 7,
                            Gia = 22000m,
                            IsNew = false,
                            IsPopular = true,
                            MaLoai = 3,
                            MoTa = "Khoai tây chiên giòn rụm, vàng óng.",
                            Rating = 4.5,
                            ReviewCount = 450,
                            TenMonAn = "Khoai Tây Chiên (Vừa)"
                        },
                        new
                        {
                            MaMonAn = 8,
                            Gia = 42000m,
                            IsNew = false,
                            IsPopular = false,
                            MaLoai = 3,
                            MoTa = "5 miếng gà viên chiên giòn.",
                            Rating = 4.4000000000000004,
                            ReviewCount = 130,
                            TenMonAn = "5 Gà Miếng Nuggets"
                        },
                        new
                        {
                            MaMonAn = 9,
                            Gia = 17000m,
                            IsNew = false,
                            IsPopular = false,
                            MaLoai = 4,
                            MoTa = "Nước ngọt có gas Pepsi mát lạnh sảng khoái.",
                            Rating = 4.5,
                            ReviewCount = 100,
                            TenMonAn = "Pepsi Lon"
                        },
                        new
                        {
                            MaMonAn = 10,
                            Gia = 18000m,
                            IsNew = false,
                            IsPopular = true,
                            MaLoai = 4,
                            MoTa = "Bánh trứng nướng thơm lừng, béo ngậy.",
                            Rating = 4.7999999999999998,
                            ReviewCount = 280,
                            TenMonAn = "Bánh Trứng"
                        });
                });

            modelBuilder.Entity("ASM1.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaCapThanhVien")
                        .HasColumnType("int");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("MaCapThanhVien");

                    b.HasIndex("MaVaiTro");

                    b.ToTable("NguoiDungs");

                    b.HasData(
                        new
                        {
                            MaNguoiDung = 1,
                            DiemTichLuy = 0,
                            Email = "admin@example.com",
                            HoTen = "Admin",
                            MaCapThanhVien = 1,
                            MaVaiTro = 1,
                            MatKhau = "$2a$11$gA9i54f.gYj02T/Iq0xV..36gT0zQL./C59Fh.Zk.K.dZ.zY.zY.O",
                            NgaySinh = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0123456789"
                        });
                });

            modelBuilder.Entity("CapThanhVien", b =>
                {
                    b.Property<int>("MaCapThanhVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCapThanhVien"));

                    b.Property<int>("NguongDiem")
                        .HasColumnType("int");

                    b.Property<double>("PhanTramGiamGia")
                        .HasColumnType("float");

                    b.Property<string>("TenCap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaCapThanhVien");

                    b.ToTable("CapThanhViens");

                    b.HasData(
                        new
                        {
                            MaCapThanhVien = 1,
                            NguongDiem = 0,
                            PhanTramGiamGia = 0.0,
                            TenCap = "Đồng"
                        },
                        new
                        {
                            MaCapThanhVien = 2,
                            NguongDiem = 300,
                            PhanTramGiamGia = 5.0,
                            TenCap = "Bạc"
                        },
                        new
                        {
                            MaCapThanhVien = 3,
                            NguongDiem = 500,
                            PhanTramGiamGia = 10.0,
                            TenCap = "Vàng"
                        });
                });

            modelBuilder.Entity("ChiTietCombo", b =>
                {
                    b.Property<int>("MaCombo")
                        .HasColumnType("int");

                    b.Property<int>("MaMonAn")
                        .HasColumnType("int");

                    b.HasKey("MaCombo", "MaMonAn");

                    b.HasIndex("MaMonAn");

                    b.ToTable("ChiTietCombos");

                    b.HasData(
                        new
                        {
                            MaCombo = 1,
                            MaMonAn = 4
                        },
                        new
                        {
                            MaCombo = 1,
                            MaMonAn = 7
                        },
                        new
                        {
                            MaCombo = 1,
                            MaMonAn = 9
                        },
                        new
                        {
                            MaCombo = 2,
                            MaMonAn = 1
                        },
                        new
                        {
                            MaCombo = 2,
                            MaMonAn = 7
                        },
                        new
                        {
                            MaCombo = 2,
                            MaMonAn = 9
                        },
                        new
                        {
                            MaCombo = 3,
                            MaMonAn = 1
                        },
                        new
                        {
                            MaCombo = 3,
                            MaMonAn = 6
                        },
                        new
                        {
                            MaCombo = 3,
                            MaMonAn = 7
                        },
                        new
                        {
                            MaCombo = 3,
                            MaMonAn = 9
                        },
                        new
                        {
                            MaCombo = 4,
                            MaMonAn = 5
                        },
                        new
                        {
                            MaCombo = 4,
                            MaMonAn = 9
                        });
                });

            modelBuilder.Entity("ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MaCombo")
                        .HasColumnType("int");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<int?>("MaMonAn")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaCombo");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaMonAn");

                    b.ToTable("ChiTietHoaDons");
                });

            modelBuilder.Entity("DiaChiNguoiDung", b =>
                {
                    b.Property<int>("MaDiaChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDiaChi"));

                    b.Property<string>("DiaChiCuThe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiNhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDiaChi");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("DiaChiNguoiDungs");
                });

            modelBuilder.Entity("VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTros");

                    b.HasData(
                        new
                        {
                            MaVaiTro = 1,
                            TenVaiTro = "Admin"
                        },
                        new
                        {
                            MaVaiTro = 2,
                            TenVaiTro = "Customer"
                        });
                });

            modelBuilder.Entity("ASM1.Models.CartItem", b =>
                {
                    b.HasOne("ASM1.Models.MonAn", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ASM1.Models.HoaDon", b =>
                {
                    b.HasOne("ASM1.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("ASM1.Models.MonAn", b =>
                {
                    b.HasOne("ASM1.Models.LoaiMonAn", "LoaiMonAn")
                        .WithMany()
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiMonAn");
                });

            modelBuilder.Entity("ASM1.Models.NguoiDung", b =>
                {
                    b.HasOne("CapThanhVien", "CapThanhVien")
                        .WithMany()
                        .HasForeignKey("MaCapThanhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VaiTro", "VaiTro")
                        .WithMany()
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CapThanhVien");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("ChiTietCombo", b =>
                {
                    b.HasOne("ASM1.Models.Combo", "Combo")
                        .WithMany("ChiTietCombos")
                        .HasForeignKey("MaCombo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASM1.Models.MonAn", "MonAn")
                        .WithMany()
                        .HasForeignKey("MaMonAn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("ChiTietHoaDon", b =>
                {
                    b.HasOne("ASM1.Models.Combo", "Combo")
                        .WithMany()
                        .HasForeignKey("MaCombo");

                    b.HasOne("ASM1.Models.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASM1.Models.MonAn", "MonAn")
                        .WithMany()
                        .HasForeignKey("MaMonAn");

                    b.Navigation("Combo");

                    b.Navigation("HoaDon");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("DiaChiNguoiDung", b =>
                {
                    b.HasOne("ASM1.Models.NguoiDung", "NguoiDung")
                        .WithMany("DiaChis")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("ASM1.Models.Combo", b =>
                {
                    b.Navigation("ChiTietCombos");
                });

            modelBuilder.Entity("ASM1.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("ASM1.Models.NguoiDung", b =>
                {
                    b.Navigation("DiaChis");
                });
#pragma warning restore 612, 618
        }
    }
}
